### ISSUE TITLE
How to get back the arrows for tabs?

### ISSUE THREAD

**Issue by 4goodapp** [Carreau/brackets-visualTabs#4]
I by far, prefer the arrows, so how to get them back please?

**Comment by Carreau** [comment]
I actually have no clue on how to make things configurable, I haven't used bracket in a  long time. But if you figured out, I''ll be happy to push an update.

**Comment by 4goodapp** [comment]
ah ok... Just by curiosity What do you use now as editor?

**Comment by c42759** [comment]
@4goodapp got to the extension folder, in my case "/home/carlos/.config/Brackets/extensions/user/carreau.visibletabs", you will see 2 .CSS files: visibleTabs.css and visibleTabs_legacy.css

RenameTabs.css to visibleTabs.css.new_version
and
rename visibleTabs_legacy.css to visibleTabs.css,

Reload Brackets and are done!

**Comment by 4goodapp** [comment]
"RenameTabs.css to visibleTabs.css.new_version"
I don't understand well what you mean there

**Comment by Carreau** [comment]
Rename `visibleTabs.css` to `visibleTabs.css.new_version`  and `visibleTabs_legacy.css` to `visibleTabs.css`. 

It does not really make that "configurable" but it should work. 

Otherwise as editor, I tried Atom (too slow) and falled back in using Vim.

**Comment by 4goodapp** [comment]
Thanks, I have Atom installed but... I think it just NEED time... too heavy for an editor... I use Brackets for HTML/CSS editing... else it's Sublime Text.
